### ISSUE TITLE
Kotori using Weewx (MQTT) - ERROR: Processing MQTT message failed from topic "weewx//loop":

### ISSUE THREAD

**Issue by TheOneWhoKnocks96** [daq-tools/kotori#5] opened 2019-05-22 14:33 UTC
Hello!!

I have a weather station Vantage Pro 2 console and i'm trying to use Kotori and Weewx to publish data into grafana and store the weather data in InfluxDB.
I'm using an MQTT broker (Mosquitto) to send and receive the data from weewx to kotori.
But i have a problem processing MQTT messages from the topic. The topic that i used is 'weewx/#'.
If anyone could please help...
This is the error (kotori.log):
     
        2019-05-22T15:24:17+0100 [kotori.daq.services.mig            ] ERROR   : Processing MQTT message failed from topic "weewx//loop":
	
        [Failure instance: Traceback: <type 'exceptions.AttributeError'>: 'dict' object has no attribute 'slot'
	/usr/lib/python2.7/threading.py:801:__bootstrap_inner
	/usr/lib/python2.7/threading.py:754:run
	/opt/kotori/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
	/opt/kotori/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork
	--- <exception caught here> ---
	/opt/kotori/lib/python2.7/site-packages/twisted/python/threadpool.py:250:inContext
	/opt/kotori/lib/python2.7/site-packages/twisted/python/threadpool.py:266:<lambda>
	/opt/kotori/lib/python2.7/site-packages/twisted/python/context.py:122:callWithContext
	/opt/kotori/lib/python2.7/site-packages/twisted/python/context.py:85:callWithContext
	/opt/kotori/lib/python2.7/site-packages/kotori/daq/services/mig.py:234:process_message
	/opt/kotori/lib/python2.7/site-packages/kotori/daq/services/mig.py:92:topology_to_storage
	/opt/kotori/lib/python2.7/site-packages/kotori/daq/intercom/strategies.py:85:topology_to_storage

**Comment by TheOneWhoKnocks96** [comment] 2019-05-22 14:49
I am using a Raspberry Pi 2 with Debian stretch

**Comment by amotl** [comment] 2019-05-22 18:39
Hi there,

thanks for writing in and for using Kotori with weeWX. It's probably just a configuration error you are experiencing.

As you can read on [1], the MQTT topic should look like `weewx/097287c4-6fb0-4aeb-a095-00d65ecb15f7/Leoni/VantagePro2/loop`. The relevant configuration snippet for `weewx.conf` would be something like
```
[StdRestful]
    [[MQTT]]
        server_url = mqtt://username:password@mqtt.example.org:1883/
        topic = weewx/{USER}/{SITE}/{NODE}
        unit_system = METRIC
```
where you would replace `{USER}/{SITE}/{NODE}` by something reasonable which matches your own topology.

With kind regards,
Andreas.

[1] https://getkotori.org/docs/applications/weewx.html

**Comment by TheOneWhoKnocks96** [comment] 2019-05-24 10:13
Hi!!
Thank you for the reply.
Because i don't always have access to the weather station console, I am using the Weewx Simulator which sends data replicating the console.
I'm trying in localhost first.
The parameters {USER}/{SITE}/{NODE} (097287c4-6fb0-4aeb-a095-00d65ecb15f7/Leoni/VantagePro2) are from where? the account of grafana or from a site that you created? 

Best Regards

**Comment by amotl** [comment] 2019-05-24 10:53
Hi there,

thanks for providing further information about your scenario.

> I am using the Weewx Simulator which sends data replicating the console.

Funny thing, we haven't been aware there's a simulator out there. Good to know!

> The parameters `{USER}/{SITE}/{NODE}` are from where?

The parameters can be chosen arbitrarily and designate the data ingress channel. As you can choose the values on your own, you are able to run an arbitrary number of data ingress channels without configuring anything. For more details about the channel addressing scheme and its background, you might enjoy reading [1].

So, just choose arbitrary values which might fit your scenario there and you should be able ingest, process and visualize as intended. Please let us know if this works for you.

With kind regards,
Andreas.

[1] https://hiveeyes.org/docs/system/acquisition/index.html#addressing

**Comment by TheOneWhoKnocks96** [comment] 2019-05-24 15:20
It worked!!
Thank you!!

**Comment by amotl** [comment] 2019-05-24 17:49
Excellent. Enjoy the data acquisition and graphing!

If you like it, we are happy to receive stars on this project.

**Comment by amotl** [comment] 2019-05-24 17:50
Let's close this issue but feel free to reopen if you have further questions.

**Closed by amotl** 2019-05-24 17:50 UTC

**Comment by TheOneWhoKnocks96** [comment] 2019-05-27 11:03
Hi there again!!
It stopped working...On friday i could see in localhost in grafana the weather data but after turn off the raspberry pi during the weekend it stopped working. Today (Monday) i started again and i couldn't received transactions to kotori. I used the topic that you told me to use (weewx/default/default/VantagePro2). 

Here's the log's of kotori:

2019-05-27T11:45:16+0100 [kotori.daq.graphing.grafana.api    ] WARN    : Problem creating instant folder: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/folders/instagraf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ceffd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
2019-05-27T11:45:16+0100 [kotori.daq.services.mig            ] INFO    : Bootstrapping MqttInfluxGrafanaService. name=service-mig-weewx, channel={'realm': 'weewx', 'mqtt_topics': 'weewx/default/default/VantagePro2', 'enable': 'true', 'type': 'application', 'app_factory': 'kotori.daq.application.mqttkit:mqttkit_application'}
2019-05-27T11:45:16+0100 [kotori.daq.storage.influx          ] INFO    : Storage target is influxdb://localhost:8086
2019-05-27T11:45:16+0100 [kotori.daq.intercom.mqtt.base      ] INFO    : Starting PahoMqttAdapter. name=mqtt-weewx, broker=localhost:1883, object=<kotori.daq.intercom.mqtt.paho.PahoMqttAdapter object at 0x72cefe10>
2019-05-27T11:45:16+0100 [kotori.daq.services.mig            ] INFO    : [weewx       ] transactions: 0.00 tps
2019-05-27T11:45:16+0100 [kotori.core                        ] INFO    : Enabling vendors []
2019-05-27T11:45:16+0100 [kotori.daq.intercom.mqtt.paho      ] INFO    : Subscribing to topics [u'weewx/default/default/VantagePro2']. client=<paho.mqtt.client.Client object at 0x72c8c3b0>
2019-05-27T11:45:16+0100 [kotori.daq.intercom.mqtt.paho      ] INFO    : Subscribing to topic 'weewx/default/default/VantagePro2'
2019-05-27T11:46:16+0100 [kotori.daq.services.mig            ] INFO    : [weewx       ] transactions: 0.00 tps
2019-05-27T11:47:16+0100 [kotori.daq.services.mig            ] INFO    : [weewx       ] transactions: 0.00 tps
2019-05-27T11:48:16+0100 [kotori.daq.services.mig            ] INFO    : [weewx       ] transactions: 0.00 tps
2019-05-27T11:49:16+0100 [kotori.daq.services.mig            ] INFO    : [weewx       ] transactions: 0.00 tps
2019-05-27T11:50:16+0100 [kotori.daq.services.mig            ] INFO    : [weewx       ] transactions: 0.00 tps
2019-05-27T11:51:16+0100 [kotori.daq.services.mig            ] INFO    : [weewx       ] transactions: 0.00 tps

**Comment by TheOneWhoKnocks96** [comment] 2019-05-27 11:18
Mqtt is publishing but i can't get the data to kotori.

May 27 12:16:17 raspberrypi weewx[607]: restx: MQTT: Published record 2019-05-27 12:16:00 WEST (1558955760)

**Comment by TheOneWhoKnocks96** [comment] 2019-05-27 11:20
I also configured (change the Mqtt topic) the file Weewx.ini from kotori: 

[weewx]
enable      = true
type        = application
realm       = weewx
mqtt_topics = weewx/default/default/VantagePro2
app_factory = kotori.daq.application.mqttkit:mqttkit_application

**Comment by TheOneWhoKnocks96** [comment] 2019-05-27 11:29
SORRY!!
I fix it... it was the topic on weewx.ini, it should be mqtt_topics = weewx/default/default/VantagePro2/loop

**Comment by amotl** [comment] 2019-05-27 11:44
Hi there,

good to hear you have been able to resolve the issue you have been observing.

Suffixing the designated topic with `/loop` in the Kotori configuration feels weird to me as I believe this will be handled internally. Maybe you've added an additional `/loop` suffix to the WeeWX MQTT Plugin configuration so the effective MQTT topic will look like `/loop/loop`?

As you can see with https://github.com/daq-tools/kotori/blob/0.22.7/etc/examples/vendors/weewx.ini#L14-L22, just setting the MQTT topic prefix to be the same as the realm with wildcarding will be totally sufficient for Kotori to pick up the data
```
[weewx]
enable      = true
type        = application
realm       = weewx
mqtt_topics = weewx/#
app_factory = kotori.daq.application.mqttkit:mqttkit_application
```

as long as the MQTT topic is correctly configured on the publisher side (here: WeeWX MQTT Plugin), which looks like that on our systems:
```
[StdRestful]
    [[MQTT]]
        server_url = mqtt://username:password@mqtt.example.org:1883/
        topic = weewx/097287c4-6fb0-4aeb-a095-00d65ecb15f7/Leoni/VantagePro2
        unit_system = METRIC
```

However, it always might happen that some semantics have changed due to more recent software versions, e.g. how the WeeWX MQTT Plugin is actually publishing data. If this is the case, we will be happy to find out.

With kind regards,
Andreas.

**Comment by amotl** [comment] 2019-05-27 11:50
While your problem might have been from a different nature (as said: glad that you solved it!), I would also like to point out that warnings like
```
2019-05-27T11:45:16+0100 [kotori.daq.graphing.grafana.api    ] WARN    : Problem creating instant folder: HTTPConnectionPool(host='localhost', port=3000): Max retries exceeded with url: /api/folders/instagraf (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x72ceffd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
```

indicate that Grafana is not running - at least it's not responding on `localhost:3000`. However, this should not have any impact on appropriate data acquisition.

**Comment by TheOneWhoKnocks96** [comment] 2019-05-27 13:37
Yes, when i had the problem Grafana didn't work but now it works fine.
Thank You!!

**Comment by TheOneWhoKnocks96** [comment] 2019-05-27 15:06
Hello there again!!
Just asking a question: Do you have packages for Centos 7?
I'm trying to install kotori on a Centos Machine instead of Raspberry pi. 


Thank you

**Comment by TheOneWhoKnocks96** [comment] 2019-08-06 16:40
Hello again!!
I just have a little question regarding the topic (weewx/default/default/VantagePro2/loop). 
In here https://getkotori.org/docs/applications/weewx.html the topic in question has all variables of the station.
My question is: 
The /loop is the representation of a multi-level wildcard, like /# ?

Best Regards.

**Comment by amotl** [comment] 2019-08-06 17:38
Dear @TheOneWhoKnocks96,

> The topic in question has all variables of the station.

That's correct.

> Is `/loop` the representation of a multi-level wildcard, like `/#`?

I believe the `/loop` suffix automatically gets added by the WeeWX MQTT plugin, so we had to account to that. Kotori has a little specialization in its belly [1] by checking for `topology.slot.startswith('loop')` in order to designate the ingress package into the "sensors" domain.

With kind regards,
Andreas.

[1] https://github.com/daq-tools/kotori/blob/5f5d9511e4a0450b67b096adaf4a87122ae22296/kotori/daq/intercom/strategies.py#L84-L89

**Comment by TheOneWhoKnocks96** [comment] 2019-08-09 14:44
Thanks for the response!!

**Comment by TheOneWhoKnocks96** [comment] 2019-08-09 14:52
Sorry, but i have another question... if you don't mind answering.

It's about the exportation of data to InfluxDB in the weewx.ini file:

; ----------------------------------------------------------------------
; Data export
; https://getkotori.org/docs/handbook/export/
; https://getkotori.org/docs/applications/forwarders/http-to-influx.html
; ----------------------------------------------------------------------
[weewx.data-export]
enable          = true

type            = application
application     = kotori.io.protocol.forwarder:boot

realm           = weewx
source          = http:/api/{realm:weewx}/{network:.*}/{gateway:.*}/{node:.*}/{slot:(data|event)}.{suffix} [GET]
target          = influxdb:/{database}?measurement={measurement}
transform       = kotori.daq.intercom.strategies:WanBusStrategy.topology_to_storage,
                  kotori.io.protocol.influx:QueryTransformer.transform

My question is about the source, target and transform options.
In the option source you utilize a HTTP GET request to the database or is to get the JSON payload published in the topic and transform it in order to put in Influx?

The target option i understand, is for defining the database and measurment where we put the data.

The transform option i don't really understand, i just know you guys transform the parameters in JSON to queries.

Thanks a lot for the help already.
Best Regards.
